export const foodItemsDummy = [
  {
    id: 2,
    name: "Pizza",
    description: "Cheesy pizza with toppings",
    modelUrl: "/models/pizza.glb",
    previewImg: "/images/pizza.jpg",
    price: "450",
    ingredients: ["Flour", "Cheese", "Tomato Sauce", "Olives", "Pepperoni"],
    energyInKcal: 550,
    category: "veg",
    rating: 2.2,
  },
  {
    id: 1,
    name: "Pasta",
    description: "Delicious Italian pasta",
    modelUrl: "/models/pasta.glb",
    previewImg: "/images/pasta.png",
    price: "250",
    ingredients: ["Wheat", "Tomato Sauce", "Cheese", "Herbs"],
    energyInKcal: 350,
    category: "nonveg",
    rating: 3.8,
  },

  {
    id: 3,
    name: "Burger",
    description: "Juicy Non-veg burger",
    modelUrl: "/models/burger.glb",
    previewImg: "/images/burger.jpg",
    price: "150",
    ingredients: ["Bun", "Veg Patty", "Lettuce", "Tomato", "Cheese"],
    energyInKcal: 400,
    category: "nonveg",
    rating: 3.0,
  },
  {
    id: 4,
    name: "Samosa",
    description: "Delicious Samosa",
    modelUrl: "/models/samosa.glb",
    previewImg: "/images/samosa.jpg",
    price: "40",
    ingredients: ["Flour", "Potato", "Peas", "Spices"],
    energyInKcal: 200,
    category: "veg",
    rating: 4.6,
  },
  {
    id: 5,
    name: "Sushi",
    description: "Mouth watering sushi.",
    modelUrl: "/models/sushi.glb",
    previewImg: "/images/sushi.jpg",
    price: "600",
    ingredients: ["Rice", "Fish", "Seaweed", "Soy Sauce"],
    energyInKcal: 300,
    category: "nonveg",
    rating: 3.2,
  },
  {
    id: 6,
    name: "Coffee",
    description: "Hot coffee",
    modelUrl: "/models/coffee.glb",
    previewImg: "/images/coffee.jpg",
    price: "120",
    ingredients: ["Water", "Coffee Beans", "Milk", "Sugar"],
    energyInKcal: 80,
    category: "veg",
    rating: 4.2,
  },
];
